[package]
name = "lsp-froggy"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.26.3"
tree-sitter-froggy = "0.1.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std"] }
tower-lsp = "0.20.0"
line-index = "0.1"